[package]
name = "freedom-node"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
quinn = "0.10"
rcgen = "0.12"
rustls = "0.21"
sha3 = "0.10"
rand = "0.8"
chacha20poly1305 = { version="0.10", features=["std"] }
futures = "0.3"
hex = "0.4"
anyhow = "1.0"